package com.example.accessingdatamysql;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.ArrayList;
import java.util.List;

@Controller // This anotation shows that this class is controller class
@RequestMapping(path = "/demo") // The url starts with /demo

public class MainController {
    @Autowired //This means to get the bean called userRespository which is auto-generated by Spring,
                //We'll use it to handle data
    private UserRepository userRepository;

    @PostMapping(path = "/add")
    public @ResponseBody String addNewUser (@RequestParam String name, @RequestParam String email){
        // @ResponseBody is the returned String in response
        // @RequestParam is parameter from GET or POST request

        User n = new User();
        n.setName(name);
        n.setEmail(email);
        userRepository.save(n);
        return "Saved";
    }

    @GetMapping(path = "/all")
    public @ResponseBody Iterable<User> getAllUsers(){
        return userRepository.findAll(); // This returns JSON OR XML with users
    }

    @RequestMapping("/user")
    public List<User> getUser(){
        List<User> users = new ArrayList<>();

        return users;
    }
}
